config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[create], module: :posts
    resources :likes, only: %i[create destroy], module: :posts
  end

  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User', inverse_of: :posts
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, presence: true
  validates :body, length: { minimum: 100, maximum: 1000 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
  has_ancestry orphan_strategy: :restrict
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :posts, foreign_key: :creator, inverse_of: :creator, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

module Posts
  class ApplicationController < ApplicationController
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < Posts::ApplicationController
    # POST /comments
    def create
      authenticate_user!
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.user_id = current_user.id

      if @comment.save
        redirect_to post_path(@comment.post), notice: t('.create_success')
      else
        redirect_to post_path(@comment.post), notice: t('.create_error')
      end
    end

    private

    def comment_params
      params.require(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    def create
      authenticate_user!
      @post = Post.find(params[:post_id])
      @like = @post.likes.find_or_create_by(user_id: current_user.id)
      redirect_to @post
    end

    def destroy
      authenticate_user!
      @post = Post.find(params[:post_id])
      @like = @post.likes.find(params[:id])
      @like.destroy if @like.user_id == current_user.id
      redirect_to @post
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:creator).order('created_at DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @like = (@post.likes.find_by(user_id: current_user.id) if user_signed_in?)
    @new_comment = PostComment.new
    @comments_tree = @post.comments.includes(:user).arrange(order: :created_at)
  end

  # GET /posts/new
  def new
    authenticate_user!
    @post = current_user.posts.build
  end

  # POST /posts
  def create
    authenticate_user!
    @categories = Category.all
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: t('.create_success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title
      = t('site_title')
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta charset="utf-8"
    == csrf_meta_tags
    == csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    meta name="viewport" content="width=device-width, initial-scale=1"

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = t('hexlet_copyright')
          | ,&nbsp;
          = Time.current.year

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .py-2.border-bottom
    .d-flex.flex-wrap.align-items-center.py-2
      .navbar.navbar-expand-md.navbar-light
        div
          = link_to root_path, class: 'navbar-brand me-md-4' do
            = image_tag asset_path('logo.png'), width: 30, alt: t('.hexlet_logo')
        div
          #navbarToggler.collapse.navbar-collapse
            ul.nav.nav-pills.flex-grow-1.navbar-nav
              - if user_signed_in?
                li.nav-link.disabled
                  = current_user.email
                li.nav-item
                  = link_to new_post_path, class: 'nav-link link-dark' do
                    = t('new_post')
                li.nav-item
                  = link_to destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: t('logout_confirmation') }, class: 'nav-link link-dark' do
                    = t('logout')
                li.nav-item
                  = link_to edit_user_registration_path, class: 'nav-link link-dark' do
                    = t('profile')
              - else
                li.nav-item
                  = link_to new_user_session_path, class: 'nav-link link-dark' do
                    = t('login')
                li.nav-item
                  = link_to new_user_registration_path, class: 'nav-link link-dark' do
                    = t('registration')

app/views/posts/_comment.html.slim
.comment-container style="margin-left: #{level * 20}px"
  .comment
    .ms-4
    .card.mt-2.rounded-0(id="comment-#{comment.id}")
      .card-header.border-0
        span.me-2
          a.me-2(type="button", href="#comment-#{comment.id}")#
        span.me-2
          = comment.user.email
        span.fs-6.text-muted
          = comment.created_at.strftime('%d %b %Y, %H:%M')
      .card-body.border-0
          = comment.content
      - if user_signed_in?
        .card-footer.border-0
          - new_comment_id = "collapseNewComment-#{comment.id}"
          a.btn.btn-link.btn-block.text-left data-bs-toggle="collapse" data-bs-target="##{new_comment_id}" aria-expanded="false" aria-controls="##{new_comment_id}"
            = t('respond')
          .collapse id="#{new_comment_id}"
            .card-body
              == render 'comment_form', parent_id: comment.id, new_comment: new_comment, post: post
      - if sub_comments.present?
          .children
            - sub_comments.each do |child, sub_children|
              = render partial: 'comment', locals: { comment: child, sub_comments: sub_children, level: level + 1, new_comment: new_comment, post: post }

app/views/posts/_comment.slim
.comment-container style=("margin-left: #{level * 20}px")
  .comment
    div.ms-4
    div.card.mt-2.rounded-0(id="comment-#{comment.id}")
      div.card-header.border-0
        span.me-2 
          a.me-2(type="button", href="#comment-#{comment.id}")#
        span.me-2
          = comment.user.email
        span.fs-6.text-muted
          = comment.created_at.strftime('%d %b %Y, %H:%M')
      div.card-body.border-0
          = comment.content
      - if user_signed_in?
        div.card-footer.border-0
          == render 'comment_form', id: comment.id

      / Рекурсивно вызываем этот же partial для дочерних комментариев
      - comment.children.each do |child|
        = render 'comment', comment: child, level: level + 1

app/views/posts/_comment_form.html.slim
div
  = simple_form_for [post, new_comment], url: post_comments_path(post) do |f|
    .form-group
      = f.text_area :content, class: 'form-control'
      = f.hidden_field :parent_id, value: parent_id
      p
      = f.submit t('leave_comment'), class: 'btn btn-primary'

app/views/posts/_form.html.slim
= simple_form_for(post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, label: t('title')
    = f.input :body, label: t('content')
    = f.association :category, label: t('category')

  .form-actions
    = f.button :submit, t('create_post'), class: 'btn btn-primary'

app/views/posts/_likes.html.slim
span
  = post.likes_count
  |&nbsp;
span
  - if user_signed_in?
    - if like.present?
      = link_to post_like_path(post_id: post.id, id: like.id), data: { turbo_method: :delete } do
        i.bi.bi-hand-thumbs-up-fill
    - else
      = link_to post_likes_path(post), data: { turbo_method: :post } do
        i.bi.bi-hand-thumbs-up
  - else
    i.bi.bi-hand-thumbs-up

app/views/posts/_post.html.slim
.card.mb-3 id="#{dom_id post}"
  .card-body
    h4
      =< post.title
    p
      =< post.body
    .d-flex.justify-content-between.small.text-muted.align-items-end
      div
        span.me-2
          = post.creator.email
        span
          = time_ago_in_words(post.created_at)
      div
        = render 'likes', post: post, like: like

app/views/posts/_post_preview.html.slim
.card.mb-3 id="#{dom_id post}"
  .card-body
    h4
      =< link_to post.title, post, style: 'color: black; text-decoration: none;'
    = simple_format(truncate(post.body, length: 100))
    p
    .text-left.small.text-muted.mt-auto
      span.me-2
        = t('liked')
        = post.likes_count
      span.me-2
        = time_ago_in_words(post.created_at)
      span.me-2
        = post.creator.email

app/views/posts/index.html.slim
h1
  = t('blog_title')
#posts
  - @posts.each do |post|
    == render 'post_preview', post: post

app/views/posts/new.html.slim
h1
  = t('new_post')

== render 'form', post: @post

br

div
  = link_to t('back_to_posts'), posts_path

app/views/posts/show.html.slim
== render @post, like: @like

.lead.mt-3
  = t('comments')
- if user_signed_in?
  == render 'comment_form', parent_id: nil, new_comment: @new_comment, post: @post

- @comments_tree.each do |comment, sub_comments|
  = render partial: 'comment', locals: { comment: comment, sub_comments: sub_comments, level: 0, new_comment: @new_comment, post: @post }